name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step to get the current date
      - name: Get the current date
        id: date
        run: echo "DATE_TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV
        
      # Ensure the repository name is lowercase
      - name: Ensure lowercase repository name
        id: repo_name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/ncaa-football-discord-bot:latest,
            ${{ secrets.DOCKER_HUB_USERNAME }}/ncaa-football-discord-bot:${{ env.DATE_TAG }},
            ghcr.io/${{ github.repository }}:latest,
            ghcr.io/${{ github.repository }}:{ env.DATE_TAG }}
          build-args: |
            STAGE=prod
