name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      #run: docker build . --file Dockerfile --build-arg="STAGE=prod" --tag ncaa-football-discord-bot:lastest
      run: docker build . --file Dockerfile --build-arg="STAGE=prod" --tag ncaa-football-discord-bot:$(date +%s)
